#!/bin/bash

if [ -f $1 ] ; then
  case $1 in
    *.tar.bz2)   tar xvjf $1 && cd $(echo $1 | sed 's/.tar.bz2//')    ;;
    *.tar.gz)    tar xvzf $1 && cd $(echo $1 | sed 's/.tar.gz//')    ;;
    *.bz2)       bunzip2 $1 && cd $(echo $1 | sed 's/.bz2//')    ;;
    *.rar)       unrar x $1 && cd $(echo $1 | sed 's/.rar//')    ;;
    *.gz)        gunzip $1 && cd $(echo $1 | sed 's/.gz//')    ;;
    *.tar)       tar xvf $1 && cd $(echo $1 | sed 's/.tar//')    ;;
    *.tbz2)      tar xvjf $1 && cd $(echo $1 | sed 's/.tbz2//')    ;;
    *.tgz)       tar xvzf $1 && cd $(echo $1 | sed 's/.tgz//')    ;;
    *.zip)       unzip $1 & cd $(echo $1 | sed 's/.zip//')    ;;
    *.Z)         uncompress $1 && cd $(echo $1 | sed 's/.Z//')    ;;
    *.7z)        7z x $1 && cd $(echo $1 | sed 's/.7z//')    ;;
    *)           echo "'$1' is an unrecognized archive format"    ;;
  esac
else
  echo "'$1' is not a valid file!"
fi
